package br.com.facilit.kanban.delivery.common;

public enum ApiErrorCode {
    RESOURCE_NOT_FOUND,
    CONFLICT,
    INVALID_REQUEST,
    VALIDATION_ERROR,
    BUSINESS_RULE_VIOLATION,
    TRANSITION_BLOCKED,
    CONFIRMATION_REQUIRED,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_ERROR
}
